server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  application:
    name: customer
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: ku
    password: pugandcorgi
  security:
    user:
      name: ku
      password: password!2E
      roles: ADMIN
  loan:
    host: http://localhost:8082/api/loan
    endpoint:
      getInfo: info

restTemplate:
  connectionTimeOut: 5000
  readTimeOut: 10000